
//=========oOOOo===========================================oOOOo==========
//  Verilog file generated by HqFpga(TM) v3.0.5 (Summer 2024) Build FT091024
//  Time : Fri Sep 13 14:14:45 2024

//  Xian Intelligence Silicon Technology, Inc.(XiST)
//========================================================================
	

// work.baud_pulse_gen(baud_pulse_gen)
module baud_pulse_gen
(
    clk,
    rst_n,
    en,
    baud_pulse
);
    input  clk;
    input  rst_n;
    input  en;
    output baud_pulse;
    wire \cnt/_n_1 ;
    wire \cnt/_n_3 ;
    wire \cnt/_n_5 ;
    wire \cnt/_n_7 ;
    wire \cnt/_n_9 ;
    wire \cnt/_n_11 ;
    wire \cnt/_n_13 ;
    wire \cnt/_n_15 ;
    wire \cnt/_n_17 ;
    wire \cnt/_n_19 ;
    wire \cnt/_n_21 ;
    wire \cnt/_n_23 ;
    wire \cnt/_n_25 ;
    wire clk_c;
    wire _n_192;
    wire _n_190;
    wire baud_pulse_c;
    wire n_7;
    wire n_8;
    wire n_9;
    wire n_10;
    wire n_11;
    wire n_12;
    wire n_13;
    wire n_14;
    wire n_15;
    wire n_16;
    wire n_17;
    wire n_18;
    wire n_19;
    wire n_20;
    wire n_21;
    wire n_0;
    wire _n_191;
    wire _n_188;
    wire _n_189;
    wire n_22;
    wire \cnt[7] ;
    wire net_extracted_nHQX0;
    wire en_c;
    wire \cnt[6] ;
    wire \cnt[4] ;
    wire \cnt[3] ;
    wire \cnt[0] ;
    wire \n_24[1] ;
    wire \n_24[2] ;
    wire \n_24[3] ;
    wire \n_24[4] ;
    wire \n_24[5] ;
    wire \n_24[6] ;
    wire \n_24[7] ;
    wire \n_24[8] ;
    wire \n_24[9] ;
    wire \n_24[10] ;
    wire \n_24[11] ;
    wire \n_24[12] ;
    wire \n_24[13] ;
    wire \n_24[14] ;
    wire rst_n_c;
    wire \cnt[15] ;
    wire \cnt[11] ;
    wire \cnt[12] ;
    wire \cnt[13] ;
    wire \cnt[14] ;
    wire \cnt[9] ;
    wire \cnt[10] ;
    wire \cnt[1] ;
    wire \cnt[2] ;
    wire \cnt[5] ;
    wire \cnt[8] ;
    wire \cnt/_n_27 ;
    wire \_i_44/n58 ;
    wire \_i_44/n64 ;
    wire \_i_44/n65 ;

    xsXORCY \cnt/bitAdd_1/xorcy 
    (
        .CI(\cnt[0] ),
        .LI(\cnt[1] ),
        .O(\n_24[1] )
    );
    xsMUXCY \cnt/bitAdd_1/muxcy 
    (
        .CI(\cnt[0] ),
        .DI(\cnt[1] ),
        .S(\cnt[1] ),
        .O(\cnt/_n_1 )
    );
    xsXORCY \cnt/bitAdd_2/xorcy 
    (
        .CI(\cnt/_n_1 ),
        .LI(\cnt[2] ),
        .O(\n_24[2] )
    );
    xsMUXCY \cnt/bitAdd_2/muxcy 
    (
        .CI(\cnt/_n_1 ),
        .DI(\cnt[2] ),
        .S(\cnt[2] ),
        .O(\cnt/_n_3 )
    );
    xsXORCY \cnt/bitAdd_3/xorcy 
    (
        .CI(\cnt/_n_3 ),
        .LI(\cnt[3] ),
        .O(\n_24[3] )
    );
    xsMUXCY \cnt/bitAdd_3/muxcy 
    (
        .CI(\cnt/_n_3 ),
        .DI(\cnt[3] ),
        .S(\cnt[3] ),
        .O(\cnt/_n_5 )
    );
    xsXORCY \cnt/bitAdd_4/xorcy 
    (
        .CI(\cnt/_n_5 ),
        .LI(\cnt[4] ),
        .O(\n_24[4] )
    );
    xsMUXCY \cnt/bitAdd_4/muxcy 
    (
        .CI(\cnt/_n_5 ),
        .DI(\cnt[4] ),
        .S(\cnt[4] ),
        .O(\cnt/_n_7 )
    );
    xsXORCY \cnt/bitAdd_5/xorcy 
    (
        .CI(\cnt/_n_7 ),
        .LI(\cnt[5] ),
        .O(\n_24[5] )
    );
    xsMUXCY \cnt/bitAdd_5/muxcy 
    (
        .CI(\cnt/_n_7 ),
        .DI(\cnt[5] ),
        .S(\cnt[5] ),
        .O(\cnt/_n_9 )
    );
    xsXORCY \cnt/bitAdd_6/xorcy 
    (
        .CI(\cnt/_n_9 ),
        .LI(\cnt[6] ),
        .O(\n_24[6] )
    );
    xsMUXCY \cnt/bitAdd_6/muxcy 
    (
        .CI(\cnt/_n_9 ),
        .DI(\cnt[6] ),
        .S(\cnt[6] ),
        .O(\cnt/_n_11 )
    );
    xsXORCY \cnt/bitAdd_7/xorcy 
    (
        .CI(\cnt/_n_11 ),
        .LI(\cnt[7] ),
        .O(\n_24[7] )
    );
    xsMUXCY \cnt/bitAdd_7/muxcy 
    (
        .CI(\cnt/_n_11 ),
        .DI(\cnt[7] ),
        .S(\cnt[7] ),
        .O(\cnt/_n_13 )
    );
    xsXORCY \cnt/bitAdd_8/xorcy 
    (
        .CI(\cnt/_n_13 ),
        .LI(\cnt[8] ),
        .O(\n_24[8] )
    );
    xsMUXCY \cnt/bitAdd_8/muxcy 
    (
        .CI(\cnt/_n_13 ),
        .DI(\cnt[8] ),
        .S(\cnt[8] ),
        .O(\cnt/_n_15 )
    );
    xsXORCY \cnt/bitAdd_9/xorcy 
    (
        .CI(\cnt/_n_15 ),
        .LI(\cnt[9] ),
        .O(\n_24[9] )
    );
    xsMUXCY \cnt/bitAdd_9/muxcy 
    (
        .CI(\cnt/_n_15 ),
        .DI(\cnt[9] ),
        .S(\cnt[9] ),
        .O(\cnt/_n_17 )
    );
    xsXORCY \cnt/bitAdd_10/xorcy 
    (
        .CI(\cnt/_n_17 ),
        .LI(\cnt[10] ),
        .O(\n_24[10] )
    );
    xsMUXCY \cnt/bitAdd_10/muxcy 
    (
        .CI(\cnt/_n_17 ),
        .DI(\cnt[10] ),
        .S(\cnt[10] ),
        .O(\cnt/_n_19 )
    );
    xsXORCY \cnt/bitAdd_11/xorcy 
    (
        .CI(\cnt/_n_19 ),
        .LI(\cnt[11] ),
        .O(\n_24[11] )
    );
    xsMUXCY \cnt/bitAdd_11/muxcy 
    (
        .CI(\cnt/_n_19 ),
        .DI(\cnt[11] ),
        .S(\cnt[11] ),
        .O(\cnt/_n_21 )
    );
    xsXORCY \cnt/bitAdd_12/xorcy 
    (
        .CI(\cnt/_n_21 ),
        .LI(\cnt[12] ),
        .O(\n_24[12] )
    );
    xsMUXCY \cnt/bitAdd_12/muxcy 
    (
        .CI(\cnt/_n_21 ),
        .DI(\cnt[12] ),
        .S(\cnt[12] ),
        .O(\cnt/_n_23 )
    );
    xsXORCY \cnt/bitAdd_13/xorcy 
    (
        .CI(\cnt/_n_23 ),
        .LI(\cnt[13] ),
        .O(\n_24[13] )
    );
    xsMUXCY \cnt/bitAdd_13/muxcy 
    (
        .CI(\cnt/_n_23 ),
        .DI(\cnt[13] ),
        .S(\cnt[13] ),
        .O(\cnt/_n_25 )
    );
    xsXORCY \cnt/bitAdd_14/xorcy 
    (
        .CI(\cnt/_n_25 ),
        .LI(\cnt[14] ),
        .O(\n_24[14] )
    );
    xsMUXCY \cnt/bitAdd_14/muxcy 
    (
        .CI(\cnt/_n_25 ),
        .DI(\cnt[14] ),
        .S(\cnt[14] ),
        .O(\cnt/_n_27 )
    );
    xsIOBI clk_pad
    (
        .I(clk),
        .O(clk_c)
    );
    xsIOBI rst_n_pad
    (
        .I(rst_n),
        .O(rst_n_c)
    );
    xsIOBI en_pad
    (
        .I(en),
        .O(en_c)
    );
    xsIOBO baud_pulse_pad
    (
        .I(baud_pulse_c),
        .O(baud_pulse)
    );
    xsMUXCY _i_41
    (
        .CI(_n_190),
        .DI(_n_191),
        .S(_n_188),
        .O(_n_192)
    );
    xsMUXCY _i_43
    (
        .CI(_n_192),
        .DI(_n_191),
        .S(_n_189),
        .O(net_extracted_nHQX0)
    );
    xsDFFSA_K1C1 \cnt_reg[15] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_22),
        .Q(\cnt[15] )
    );
    xsDFFSA_K1C1 \cnt_reg[14] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_21),
        .Q(\cnt[14] )
    );
    xsDFFSA_K1C1 \cnt_reg[13] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_20),
        .Q(\cnt[13] )
    );
    xsDFFSA_K1C1 \cnt_reg[12] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_19),
        .Q(\cnt[12] )
    );
    xsDFFSA_K1C1 \cnt_reg[11] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_18),
        .Q(\cnt[11] )
    );
    xsDFFSA_K1C1 \cnt_reg[10] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_17),
        .Q(\cnt[10] )
    );
    xsDFFSA_K1C1 \cnt_reg[9] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_16),
        .Q(\cnt[9] )
    );
    xsDFFSA_K1C1 \cnt_reg[8] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_15),
        .Q(\cnt[8] )
    );
    xsDFFSA_K1C1 \cnt_reg[7] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_14),
        .Q(\cnt[7] )
    );
    xsDFFSA_K1C1 \cnt_reg[6] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_13),
        .Q(\cnt[6] )
    );
    xsDFFSA_K1C1 \cnt_reg[5] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_12),
        .Q(\cnt[5] )
    );
    xsDFFSA_K1C1 \cnt_reg[4] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_11),
        .Q(\cnt[4] )
    );
    xsDFFSA_K1C1 \cnt_reg[3] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_10),
        .Q(\cnt[3] )
    );
    xsDFFSA_K1C1 \cnt_reg[2] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_9),
        .Q(\cnt[2] )
    );
    xsDFFSA_K1C1 \cnt_reg[1] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_8),
        .Q(\cnt[1] )
    );
    xsDFFSA_K1C1 \cnt_reg[0] 
    (
        .C(clk_c),
        .CLR(n_0),
        .D(n_7),
        .Q(\cnt[0] )
    );
    xsLUTSA4 \_i_44/_i_1 
    (
        .I0(\_i_44/n58 ),
        .I1(\cnt[7] ),
        .I2(net_extracted_nHQX0),
        .I3(en_c),
        .O(baud_pulse_c)
    );
    defparam \_i_44/_i_1 .INIT = 16'H2000;

    xsLUTSA4 \_i_44/_i_2 
    (
        .I0(\cnt[6] ),
        .I1(\cnt[4] ),
        .I2(\cnt[3] ),
        .I3(\cnt[0] ),
        .O(\_i_44/n58 )
    );
    defparam \_i_44/_i_2 .INIT = 16'H0100;

    xsLUTSA4 \_i_44/_i_7 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(\cnt[0] ),
        .I3(en_c),
        .O(n_7)
    );
    defparam \_i_44/_i_7 .INIT = 16'H0700;

    xsLUTSA3 \_i_44/_i_8 
    (
        .I0(\cnt[3] ),
        .I1(\cnt[0] ),
        .I2(net_extracted_nHQX0),
        .O(\_i_44/n64 )
    );
    defparam \_i_44/_i_8 .INIT = 8'H20;

    xsLUTSA3 \_i_44/_i_9 
    (
        .I0(\cnt[7] ),
        .I1(\cnt[6] ),
        .I2(\cnt[4] ),
        .O(\_i_44/n65 )
    );
    defparam \_i_44/_i_9 .INIT = 8'H80;

    xsLUTSA4 \_i_44/_i_10 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[1] ),
        .O(n_8)
    );
    defparam \_i_44/_i_10 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_11 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[2] ),
        .O(n_9)
    );
    defparam \_i_44/_i_11 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_12 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[3] ),
        .O(n_10)
    );
    defparam \_i_44/_i_12 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_13 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[4] ),
        .O(n_11)
    );
    defparam \_i_44/_i_13 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_14 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[5] ),
        .O(n_12)
    );
    defparam \_i_44/_i_14 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_15 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[6] ),
        .O(n_13)
    );
    defparam \_i_44/_i_15 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_16 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[7] ),
        .O(n_14)
    );
    defparam \_i_44/_i_16 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_17 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[8] ),
        .O(n_15)
    );
    defparam \_i_44/_i_17 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_18 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[9] ),
        .O(n_16)
    );
    defparam \_i_44/_i_18 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_19 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[10] ),
        .O(n_17)
    );
    defparam \_i_44/_i_19 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_20 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[11] ),
        .O(n_18)
    );
    defparam \_i_44/_i_20 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_21 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[12] ),
        .O(n_19)
    );
    defparam \_i_44/_i_21 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_22 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[13] ),
        .O(n_20)
    );
    defparam \_i_44/_i_22 .INIT = 16'H7000;

    xsLUTSA4 \_i_44/_i_23 
    (
        .I0(\_i_44/n64 ),
        .I1(\_i_44/n65 ),
        .I2(en_c),
        .I3(\n_24[14] ),
        .O(n_21)
    );
    defparam \_i_44/_i_23 .INIT = 16'H7000;

    xsINVSA \_i_44/_i_26 
    (
        .I(rst_n_c),
        .O(n_0)
    );
    xsLUTSA5 _i_0
    (
        .I0(\cnt[15] ),
        .I1(\cnt[11] ),
        .I2(\cnt[12] ),
        .I3(\cnt[13] ),
        .I4(\cnt[14] ),
        .O(_n_188)
    );
    defparam _i_0.INIT = 32'H00000001;

    xsLUTSA6 _i_1
    (
        .I0(\cnt[9] ),
        .I1(\cnt[10] ),
        .I2(\cnt[1] ),
        .I3(\cnt[2] ),
        .I4(\cnt[5] ),
        .I5(\cnt[8] ),
        .O(_n_189)
    );
    defparam _i_1.INIT = 64'H0000000000000001;

    xsLUTSA5 _i_2
    (
        .I0(en_c),
        .I1(\cnt[15] ),
        .I2(\cnt/_n_27 ),
        .I3(\_i_44/n64 ),
        .I4(\_i_44/n65 ),
        .O(n_22)
    );
    defparam _i_2.INIT = 32'H00282828;

    xs1 \_i_44/_i_0 
    (
        .P(_n_190)
    );
    xs0 \_i_44/_i_27 
    (
        .G(_n_191)
    );


endmodule
