
//=========oOOOo===========================================oOOOo==========
//  Verilog file generated by HqFpga(TM) v3.0.5 (Summer 2024) Build FT091024
//  Time : Sat Sep 14 10:00:13 2024

//  Xian Intelligence Silicon Technology, Inc.(XiST)
//========================================================================
	

// work.uart_demo(uart_demo)
module uart_demo
(
    clk,
    rst_n,
    uart_rx,
    uart_tx
);
    input  clk;
    input  rst_n;
    input  uart_rx;
    output uart_tx;
    wire [7:0] rx_byte;
    wire \u_baud_pulse_gen/cnt/_n_1 ;
    wire \u_baud_pulse_gen/cnt/_n_3 ;
    wire \u_baud_pulse_gen/cnt/_n_5 ;
    wire \u_baud_pulse_gen/cnt/_n_7 ;
    wire \u_baud_pulse_gen/cnt/_n_9 ;
    wire \u_baud_pulse_gen/cnt/_n_11 ;
    wire \u_baud_pulse_gen/cnt/_n_13 ;
    wire \u_baud_pulse_gen/cnt/_n_15 ;
    wire \u_baud_pulse_gen/cnt/_n_17 ;
    wire \u_baud_pulse_gen/cnt/_n_19 ;
    wire \u_baud_pulse_gen/cnt/_n_21 ;
    wire \u_baud_pulse_gen/cnt/_n_23 ;
    wire \u_baud_pulse_gen/cnt/_n_25 ;
    wire clk_c;
    wire \u_uart_rx/curr_state_reg_0_ctrl_din ;
    wire \u_uart_tx/curr_state_reg_0_ctrl_din ;
    wire \u_loop_ctrl/tx_req_reg_ctrl_din ;
    wire rx_valid;
    wire \u_uart_rx/n_74[1] ;
    wire \u_uart_rx/n_74[2] ;
    wire \u_uart_rx/n_73 ;
    wire \u_uart_tx/n_41[1] ;
    wire \u_uart_tx/n_41[2] ;
    wire \u_uart_tx/n_37 ;
    wire \u_uart_tx/n_36 ;
    wire \u_uart_tx/n_35 ;
    wire \u_uart_tx/n_34 ;
    wire \u_uart_tx/n_33 ;
    wire \u_uart_tx/n_32 ;
    wire \u_uart_tx/n_31 ;
    wire \u_uart_tx/n_30 ;
    wire \u_uart_tx/n_29 ;
    wire \u_uart_tx/n_40 ;
    wire \u_baud_pulse_gen/n_4 ;
    wire \u_baud_pulse_gen/n_5 ;
    wire \u_baud_pulse_gen/n_6 ;
    wire \u_baud_pulse_gen/n_7 ;
    wire \u_baud_pulse_gen/n_8 ;
    wire \u_baud_pulse_gen/n_9 ;
    wire \u_baud_pulse_gen/n_10 ;
    wire \u_baud_pulse_gen/n_11 ;
    wire \u_baud_pulse_gen/n_12 ;
    wire \u_baud_pulse_gen/n_13 ;
    wire \u_baud_pulse_gen/n_14 ;
    wire \u_baud_pulse_gen/n_15 ;
    wire \u_baud_pulse_gen/n_16 ;
    wire \u_baud_pulse_gen/n_17 ;
    wire \u_baud_pulse_gen/n_18 ;
    wire \u_baud_pulse_gen/n_19 ;
    wire \u_uart_rx/n_74[0] ;
    wire \u_uart_tx/n_41[0] ;
    wire \u_baud_pulse_gen/n_0 ;
    wire \u_uart_rx/n_88 ;
    wire \u_uart_tx/n_56 ;
    wire \u_uart_tx/tx_reg_ctrl_din ;
    wire \u_uart_tx/busy_reg_ctrl_din ;
    wire \u_uart_rx/n_78 ;
    wire \u_uart_rx/n_76 ;
    wire \u_uart_tx/n_47 ;
    wire \u_uart_tx/n_45 ;
    wire tx_busy;
    wire tx_req;
    wire \u_uart_rx/data_baud_cnt[0] ;
    wire \u_uart_rx/data_baud_cnt[1] ;
    wire \u_uart_rx/data_baud_cnt[2] ;
    wire \u_uart_tx/data_baud_cnt[0] ;
    wire \u_uart_tx/data_baud_cnt[1] ;
    wire \u_uart_tx/data_baud_cnt[2] ;
    wire \u_uart_tx/byte_in_reg[6] ;
    wire \tx_byte[7] ;
    wire \u_uart_tx/byte_in_reg[5] ;
    wire \tx_byte[6] ;
    wire \u_uart_tx/byte_in_reg[4] ;
    wire \tx_byte[5] ;
    wire \u_uart_tx/byte_in_reg[3] ;
    wire \tx_byte[4] ;
    wire \u_uart_tx/byte_in_reg[2] ;
    wire \tx_byte[3] ;
    wire \u_uart_tx/byte_in_reg[1] ;
    wire \tx_byte[2] ;
    wire \u_uart_tx/byte_in_reg[0] ;
    wire \tx_byte[1] ;
    wire \tx_byte[0] ;
    wire \u_baud_pulse_gen/cnt[0] ;
    wire \u_baud_pulse_gen/n_22[1] ;
    wire \u_baud_pulse_gen/n_22[2] ;
    wire \u_baud_pulse_gen/n_22[3] ;
    wire \u_baud_pulse_gen/n_22[4] ;
    wire \u_baud_pulse_gen/n_22[5] ;
    wire \u_baud_pulse_gen/n_22[6] ;
    wire \u_baud_pulse_gen/n_22[7] ;
    wire \u_baud_pulse_gen/n_22[8] ;
    wire \u_baud_pulse_gen/n_22[9] ;
    wire \u_baud_pulse_gen/n_22[10] ;
    wire \u_baud_pulse_gen/n_22[11] ;
    wire \u_baud_pulse_gen/n_22[12] ;
    wire \u_baud_pulse_gen/n_22[13] ;
    wire \u_baud_pulse_gen/n_22[14] ;
    wire \u_baud_pulse_gen/cnt[15] ;
    wire \u_baud_pulse_gen/cnt/_n_27 ;
    wire rst_n_c;
    wire \u_baud_pulse_gen/cnt[7] ;
    wire \u_baud_pulse_gen/cnt[6] ;
    wire \u_baud_pulse_gen/cnt[5] ;
    wire \u_baud_pulse_gen/cnt[4] ;
    wire \u_baud_pulse_gen/cnt[11] ;
    wire \u_baud_pulse_gen/cnt[10] ;
    wire \u_baud_pulse_gen/cnt[9] ;
    wire \u_baud_pulse_gen/cnt[8] ;
    wire \u_baud_pulse_gen/cnt[14] ;
    wire \u_baud_pulse_gen/cnt[13] ;
    wire \u_baud_pulse_gen/cnt[12] ;
    wire \u_baud_pulse_gen/cnt[3] ;
    wire \u_baud_pulse_gen/cnt[2] ;
    wire \u_baud_pulse_gen/cnt[1] ;
    wire uart_rx_c;
    wire uart_tx_c;
    wire \u_uart_tx/byte_in_reg[7] ;
    wire \_i_3/n113 ;
    wire \_i_3/n119 ;
    wire \_i_3/n125 ;
    wire \_i_3/n129 ;
    wire _n_0;
    wire _n_1;
    wire \_i_3/n106 ;
    wire \_i_3/n127 ;

    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_1/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt[0] ),
        .LI(\u_baud_pulse_gen/cnt[1] ),
        .O(\u_baud_pulse_gen/n_22[1] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_1/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt[0] ),
        .DI(\u_baud_pulse_gen/cnt[1] ),
        .S(\u_baud_pulse_gen/cnt[1] ),
        .O(\u_baud_pulse_gen/cnt/_n_1 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_2/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_1 ),
        .LI(\u_baud_pulse_gen/cnt[2] ),
        .O(\u_baud_pulse_gen/n_22[2] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_2/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_1 ),
        .DI(\u_baud_pulse_gen/cnt[2] ),
        .S(\u_baud_pulse_gen/cnt[2] ),
        .O(\u_baud_pulse_gen/cnt/_n_3 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_3/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_3 ),
        .LI(\u_baud_pulse_gen/cnt[3] ),
        .O(\u_baud_pulse_gen/n_22[3] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_3/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_3 ),
        .DI(\u_baud_pulse_gen/cnt[3] ),
        .S(\u_baud_pulse_gen/cnt[3] ),
        .O(\u_baud_pulse_gen/cnt/_n_5 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_4/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_5 ),
        .LI(\u_baud_pulse_gen/cnt[4] ),
        .O(\u_baud_pulse_gen/n_22[4] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_4/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_5 ),
        .DI(\u_baud_pulse_gen/cnt[4] ),
        .S(\u_baud_pulse_gen/cnt[4] ),
        .O(\u_baud_pulse_gen/cnt/_n_7 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_5/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_7 ),
        .LI(\u_baud_pulse_gen/cnt[5] ),
        .O(\u_baud_pulse_gen/n_22[5] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_5/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_7 ),
        .DI(\u_baud_pulse_gen/cnt[5] ),
        .S(\u_baud_pulse_gen/cnt[5] ),
        .O(\u_baud_pulse_gen/cnt/_n_9 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_6/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_9 ),
        .LI(\u_baud_pulse_gen/cnt[6] ),
        .O(\u_baud_pulse_gen/n_22[6] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_6/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_9 ),
        .DI(\u_baud_pulse_gen/cnt[6] ),
        .S(\u_baud_pulse_gen/cnt[6] ),
        .O(\u_baud_pulse_gen/cnt/_n_11 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_7/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_11 ),
        .LI(\u_baud_pulse_gen/cnt[7] ),
        .O(\u_baud_pulse_gen/n_22[7] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_7/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_11 ),
        .DI(\u_baud_pulse_gen/cnt[7] ),
        .S(\u_baud_pulse_gen/cnt[7] ),
        .O(\u_baud_pulse_gen/cnt/_n_13 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_8/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_13 ),
        .LI(\u_baud_pulse_gen/cnt[8] ),
        .O(\u_baud_pulse_gen/n_22[8] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_8/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_13 ),
        .DI(\u_baud_pulse_gen/cnt[8] ),
        .S(\u_baud_pulse_gen/cnt[8] ),
        .O(\u_baud_pulse_gen/cnt/_n_15 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_9/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_15 ),
        .LI(\u_baud_pulse_gen/cnt[9] ),
        .O(\u_baud_pulse_gen/n_22[9] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_9/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_15 ),
        .DI(\u_baud_pulse_gen/cnt[9] ),
        .S(\u_baud_pulse_gen/cnt[9] ),
        .O(\u_baud_pulse_gen/cnt/_n_17 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_10/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_17 ),
        .LI(\u_baud_pulse_gen/cnt[10] ),
        .O(\u_baud_pulse_gen/n_22[10] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_10/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_17 ),
        .DI(\u_baud_pulse_gen/cnt[10] ),
        .S(\u_baud_pulse_gen/cnt[10] ),
        .O(\u_baud_pulse_gen/cnt/_n_19 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_11/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_19 ),
        .LI(\u_baud_pulse_gen/cnt[11] ),
        .O(\u_baud_pulse_gen/n_22[11] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_11/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_19 ),
        .DI(\u_baud_pulse_gen/cnt[11] ),
        .S(\u_baud_pulse_gen/cnt[11] ),
        .O(\u_baud_pulse_gen/cnt/_n_21 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_12/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_21 ),
        .LI(\u_baud_pulse_gen/cnt[12] ),
        .O(\u_baud_pulse_gen/n_22[12] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_12/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_21 ),
        .DI(\u_baud_pulse_gen/cnt[12] ),
        .S(\u_baud_pulse_gen/cnt[12] ),
        .O(\u_baud_pulse_gen/cnt/_n_23 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_13/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_23 ),
        .LI(\u_baud_pulse_gen/cnt[13] ),
        .O(\u_baud_pulse_gen/n_22[13] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_13/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_23 ),
        .DI(\u_baud_pulse_gen/cnt[13] ),
        .S(\u_baud_pulse_gen/cnt[13] ),
        .O(\u_baud_pulse_gen/cnt/_n_25 )
    );
    xsXORCY \u_baud_pulse_gen/cnt/bitAdd_14/xorcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_25 ),
        .LI(\u_baud_pulse_gen/cnt[14] ),
        .O(\u_baud_pulse_gen/n_22[14] )
    );
    xsMUXCY \u_baud_pulse_gen/cnt/bitAdd_14/muxcy 
    (
        .CI(\u_baud_pulse_gen/cnt/_n_25 ),
        .DI(\u_baud_pulse_gen/cnt[14] ),
        .S(\u_baud_pulse_gen/cnt[14] ),
        .O(\u_baud_pulse_gen/cnt/_n_27 )
    );
    xsIOBI clk_pad
    (
        .I(clk),
        .O(clk_c)
    );
    xsIOBI rst_n_pad
    (
        .I(rst_n),
        .O(rst_n_c)
    );
    xsIOBI uart_rx_pad
    (
        .I(uart_rx),
        .O(uart_rx_c)
    );
    xsIOBO uart_tx_pad
    (
        .I(uart_tx_c),
        .O(uart_tx)
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[15] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_19 ),
        .Q(\u_baud_pulse_gen/cnt[15] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[14] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_18 ),
        .Q(\u_baud_pulse_gen/cnt[14] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[13] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_17 ),
        .Q(\u_baud_pulse_gen/cnt[13] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[12] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_16 ),
        .Q(\u_baud_pulse_gen/cnt[12] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[11] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_15 ),
        .Q(\u_baud_pulse_gen/cnt[11] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[10] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_14 ),
        .Q(\u_baud_pulse_gen/cnt[10] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[9] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_13 ),
        .Q(\u_baud_pulse_gen/cnt[9] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[8] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_12 ),
        .Q(\u_baud_pulse_gen/cnt[8] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[7] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_11 ),
        .Q(\u_baud_pulse_gen/cnt[7] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[6] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_10 ),
        .Q(\u_baud_pulse_gen/cnt[6] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[5] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_9 ),
        .Q(\u_baud_pulse_gen/cnt[5] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[4] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_8 ),
        .Q(\u_baud_pulse_gen/cnt[4] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[3] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_7 ),
        .Q(\u_baud_pulse_gen/cnt[3] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[2] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_6 ),
        .Q(\u_baud_pulse_gen/cnt[2] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[1] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_5 ),
        .Q(\u_baud_pulse_gen/cnt[1] )
    );
    xsDFFSA_K1C1 \u_baud_pulse_gen/cnt_reg[0] 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_baud_pulse_gen/n_4 ),
        .Q(\u_baud_pulse_gen/cnt[0] )
    );
    xsDFFSA_K1C1E1 \u_uart_tx/byte_in_reg_reg[0] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_29 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_tx/n_30 ),
        .Q(\u_uart_tx/byte_in_reg[0] )
    );
    xsDFFSA_K1C1E1 \u_uart_tx/byte_in_reg_reg[1] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_29 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_tx/n_31 ),
        .Q(\u_uart_tx/byte_in_reg[1] )
    );
    xsDFFSA_K1C1E1 \u_uart_tx/byte_in_reg_reg[2] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_29 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_tx/n_32 ),
        .Q(\u_uart_tx/byte_in_reg[2] )
    );
    xsDFFSA_K1C1E1 \u_uart_tx/byte_in_reg_reg[3] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_29 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_tx/n_33 ),
        .Q(\u_uart_tx/byte_in_reg[3] )
    );
    xsDFFSA_K1C1E1 \u_uart_tx/byte_in_reg_reg[4] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_29 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_tx/n_34 ),
        .Q(\u_uart_tx/byte_in_reg[4] )
    );
    xsDFFSA_K1C1E1 \u_uart_tx/byte_in_reg_reg[5] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_29 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_tx/n_35 ),
        .Q(\u_uart_tx/byte_in_reg[5] )
    );
    xsDFFSA_K1C1E1 \u_uart_tx/byte_in_reg_reg[6] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_29 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_tx/n_36 ),
        .Q(\u_uart_tx/byte_in_reg[6] )
    );
    xsDFFSA_K1C1E1 \u_uart_tx/byte_in_reg_reg[7] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_29 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_tx/n_37 ),
        .Q(\u_uart_tx/byte_in_reg[7] )
    );
    xsDFFSA_K1C1 \u_uart_tx/busy_reg 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_tx/busy_reg_ctrl_din ),
        .Q(tx_busy)
    );
    xsDFFSA_K1P1 \u_uart_tx/tx_reg 
    (
        .C(clk_c),
        .D(\u_uart_tx/tx_reg_ctrl_din ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(uart_tx_c)
    );
    xsDFFSA_K1P1 \u_uart_tx/curr_state_reg_1 
    (
        .C(clk_c),
        .D(\u_uart_tx/n_56 ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(\u_uart_tx/n_47 )
    );
    defparam \u_uart_tx/curr_state_reg_1 .INIT = 1'B1;

    xsDFFSA_K1P1E1 \u_uart_tx/data_baud_cnt_reg[2] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_40 ),
        .D(\u_uart_tx/n_41[2] ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(\u_uart_tx/data_baud_cnt[2] )
    );
    xsDFFSA_K1P1E1 \u_uart_tx/data_baud_cnt_reg[1] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_40 ),
        .D(\u_uart_tx/n_41[1] ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(\u_uart_tx/data_baud_cnt[1] )
    );
    xsDFFSA_K1P1E1 \u_uart_tx/data_baud_cnt_reg[0] 
    (
        .C(clk_c),
        .CE(\u_uart_tx/n_40 ),
        .D(\u_uart_tx/n_41[0] ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(\u_uart_tx/data_baud_cnt[0] )
    );
    xsDFFSA_K1C1E1 \u_uart_rx/byte_out_reg[0] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(uart_rx_c),
        .Q(rx_byte[0])
    );
    xsDFFSA_K1C1E1 \u_uart_rx/byte_out_reg[1] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[0]),
        .Q(rx_byte[1])
    );
    xsDFFSA_K1C1E1 \u_uart_rx/byte_out_reg[2] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[1]),
        .Q(rx_byte[2])
    );
    xsDFFSA_K1C1E1 \u_uart_rx/byte_out_reg[3] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[2]),
        .Q(rx_byte[3])
    );
    xsDFFSA_K1C1E1 \u_uart_rx/byte_out_reg[4] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[3]),
        .Q(rx_byte[4])
    );
    xsDFFSA_K1C1E1 \u_uart_rx/byte_out_reg[5] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[4]),
        .Q(rx_byte[5])
    );
    xsDFFSA_K1C1E1 \u_uart_rx/byte_out_reg[6] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[5]),
        .Q(rx_byte[6])
    );
    xsDFFSA_K1C1E1 \u_uart_rx/byte_out_reg[7] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[6]),
        .Q(rx_byte[7])
    );
    xsDFFSA_K1C1 \u_uart_rx/curr_state_reg_1 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_uart_rx/n_88 ),
        .Q(\u_uart_rx/n_78 )
    );
    defparam \u_uart_rx/curr_state_reg_1 .INIT = 1'B0;

    xsDFFSA_K1P1E1 \u_uart_rx/data_baud_cnt_reg[2] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .D(\u_uart_rx/n_74[2] ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(\u_uart_rx/data_baud_cnt[2] )
    );
    xsDFFSA_K1P1E1 \u_uart_rx/data_baud_cnt_reg[1] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .D(\u_uart_rx/n_74[1] ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(\u_uart_rx/data_baud_cnt[1] )
    );
    xsDFFSA_K1P1E1 \u_uart_rx/data_baud_cnt_reg[0] 
    (
        .C(clk_c),
        .CE(\u_uart_rx/n_73 ),
        .D(\u_uart_rx/n_74[0] ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(\u_uart_rx/data_baud_cnt[0] )
    );
    xsDFFSA_K1C1 \u_loop_ctrl/tx_req_reg 
    (
        .C(clk_c),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(\u_loop_ctrl/tx_req_reg_ctrl_din ),
        .Q(tx_req)
    );
    xsDFFSA_K1C1E1 \u_loop_ctrl/byte_out_reg[7] 
    (
        .C(clk_c),
        .CE(rx_valid),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[7]),
        .Q(\tx_byte[7] )
    );
    xsDFFSA_K1C1E1 \u_loop_ctrl/byte_out_reg[6] 
    (
        .C(clk_c),
        .CE(rx_valid),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[6]),
        .Q(\tx_byte[6] )
    );
    xsDFFSA_K1C1E1 \u_loop_ctrl/byte_out_reg[5] 
    (
        .C(clk_c),
        .CE(rx_valid),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[5]),
        .Q(\tx_byte[5] )
    );
    xsDFFSA_K1C1E1 \u_loop_ctrl/byte_out_reg[4] 
    (
        .C(clk_c),
        .CE(rx_valid),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[4]),
        .Q(\tx_byte[4] )
    );
    xsDFFSA_K1C1E1 \u_loop_ctrl/byte_out_reg[3] 
    (
        .C(clk_c),
        .CE(rx_valid),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[3]),
        .Q(\tx_byte[3] )
    );
    xsDFFSA_K1C1E1 \u_loop_ctrl/byte_out_reg[2] 
    (
        .C(clk_c),
        .CE(rx_valid),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[2]),
        .Q(\tx_byte[2] )
    );
    xsDFFSA_K1C1E1 \u_loop_ctrl/byte_out_reg[1] 
    (
        .C(clk_c),
        .CE(rx_valid),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[1]),
        .Q(\tx_byte[1] )
    );
    xsDFFSA_K1C1E1 \u_loop_ctrl/byte_out_reg[0] 
    (
        .C(clk_c),
        .CE(rx_valid),
        .CLR(\u_baud_pulse_gen/n_0 ),
        .D(rx_byte[0]),
        .Q(\tx_byte[0] )
    );
    xsDFFSA_K1P1 \u_uart_tx/curr_state_reg_0 
    (
        .C(clk_c),
        .D(\u_uart_tx/curr_state_reg_0_ctrl_din ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(\u_uart_tx/n_45 )
    );
    defparam \u_uart_tx/curr_state_reg_0 .INIT = 1'B1;

    xsDFFSA_K1P1 \u_uart_rx/curr_state_reg_0 
    (
        .C(clk_c),
        .D(\u_uart_rx/curr_state_reg_0_ctrl_din ),
        .PRE(\u_baud_pulse_gen/n_0 ),
        .Q(\u_uart_rx/n_76 )
    );
    defparam \u_uart_rx/curr_state_reg_0 .INIT = 1'B1;

    xsLUTSA3 \_i_3/_i_0 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_uart_rx/n_78 ),
        .I2(\u_uart_rx/n_76 ),
        .O(\u_uart_rx/curr_state_reg_0_ctrl_din )
    );
    defparam \_i_3/_i_0 .INIT = 8'H72;

    xsLUTSA3 \_i_3/_i_6 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_uart_tx/n_47 ),
        .I2(\u_uart_tx/n_45 ),
        .O(\u_uart_tx/curr_state_reg_0_ctrl_din )
    );
    defparam \_i_3/_i_6 .INIT = 8'HD8;

    xsLUTSA4 \_i_3/_i_7 
    (
        .I0(\_i_3/n106 ),
        .I1(\_i_3/n113 ),
        .I2(tx_busy),
        .I3(tx_req),
        .O(\u_loop_ctrl/tx_req_reg_ctrl_din )
    );
    defparam \_i_3/_i_7 .INIT = 16'H8F88;

    xsLUTSA2 \_i_3/_i_8 
    (
        .I0(\u_uart_rx/n_78 ),
        .I1(\u_uart_rx/n_76 ),
        .O(\_i_3/n113 )
    );
    defparam \_i_3/_i_8 .INIT = 4'H1;

    xsLUTSA2 \_i_3/_i_9 
    (
        .I0(\_i_3/n106 ),
        .I1(\_i_3/n113 ),
        .O(rx_valid)
    );
    defparam \_i_3/_i_9 .INIT = 4'H8;

    xsLUTSA2 \_i_3/_i_10 
    (
        .I0(\u_uart_rx/data_baud_cnt[0] ),
        .I1(\u_uart_rx/data_baud_cnt[1] ),
        .O(\u_uart_rx/n_74[1] )
    );
    defparam \_i_3/_i_10 .INIT = 4'H6;

    xsLUTSA3 \_i_3/_i_11 
    (
        .I0(\u_uart_rx/data_baud_cnt[0] ),
        .I1(\u_uart_rx/data_baud_cnt[1] ),
        .I2(\u_uart_rx/data_baud_cnt[2] ),
        .O(\u_uart_rx/n_74[2] )
    );
    defparam \_i_3/_i_11 .INIT = 8'H78;

    xsLUTSA4 \_i_3/_i_14 
    (
        .I0(\u_uart_rx/n_76 ),
        .I1(\u_uart_rx/data_baud_cnt[0] ),
        .I2(\u_uart_rx/data_baud_cnt[1] ),
        .I3(\u_uart_rx/data_baud_cnt[2] ),
        .O(\_i_3/n119 )
    );
    defparam \_i_3/_i_14 .INIT = 16'H4000;

    xsLUTSA3 \_i_3/_i_15 
    (
        .I0(\_i_3/n106 ),
        .I1(\_i_3/n119 ),
        .I2(\u_uart_rx/n_78 ),
        .O(\u_uart_rx/n_73 )
    );
    defparam \_i_3/_i_15 .INIT = 8'H20;

    xsLUTSA2 \_i_3/_i_16 
    (
        .I0(\u_uart_tx/data_baud_cnt[0] ),
        .I1(\u_uart_tx/data_baud_cnt[1] ),
        .O(\u_uart_tx/n_41[1] )
    );
    defparam \_i_3/_i_16 .INIT = 4'H6;

    xsLUTSA3 \_i_3/_i_17 
    (
        .I0(\u_uart_tx/data_baud_cnt[0] ),
        .I1(\u_uart_tx/data_baud_cnt[1] ),
        .I2(\u_uart_tx/data_baud_cnt[2] ),
        .O(\u_uart_tx/n_41[2] )
    );
    defparam \_i_3/_i_17 .INIT = 8'H78;

    xsLUTSA3 \_i_3/_i_20 
    (
        .I0(\u_uart_tx/data_baud_cnt[0] ),
        .I1(\u_uart_tx/data_baud_cnt[1] ),
        .I2(\u_uart_tx/data_baud_cnt[2] ),
        .O(\_i_3/n125 )
    );
    defparam \_i_3/_i_20 .INIT = 8'H80;

    xsLUTSA4 \_i_3/_i_24 
    (
        .I0(\u_uart_tx/n_45 ),
        .I1(\u_uart_tx/data_baud_cnt[0] ),
        .I2(\u_uart_tx/data_baud_cnt[1] ),
        .I3(\u_uart_tx/data_baud_cnt[2] ),
        .O(\_i_3/n129 )
    );
    defparam \_i_3/_i_24 .INIT = 16'H4000;

    xsLUTSA3 \_i_3/_i_28 
    (
        .I0(tx_req),
        .I1(\u_uart_tx/byte_in_reg[6] ),
        .I2(\tx_byte[7] ),
        .O(\u_uart_tx/n_37 )
    );
    defparam \_i_3/_i_28 .INIT = 8'HE4;

    xsLUTSA3 \_i_3/_i_29 
    (
        .I0(tx_req),
        .I1(\u_uart_tx/byte_in_reg[5] ),
        .I2(\tx_byte[6] ),
        .O(\u_uart_tx/n_36 )
    );
    defparam \_i_3/_i_29 .INIT = 8'HE4;

    xsLUTSA3 \_i_3/_i_30 
    (
        .I0(tx_req),
        .I1(\u_uart_tx/byte_in_reg[4] ),
        .I2(\tx_byte[5] ),
        .O(\u_uart_tx/n_35 )
    );
    defparam \_i_3/_i_30 .INIT = 8'HE4;

    xsLUTSA3 \_i_3/_i_31 
    (
        .I0(tx_req),
        .I1(\u_uart_tx/byte_in_reg[3] ),
        .I2(\tx_byte[4] ),
        .O(\u_uart_tx/n_34 )
    );
    defparam \_i_3/_i_31 .INIT = 8'HE4;

    xsLUTSA3 \_i_3/_i_32 
    (
        .I0(tx_req),
        .I1(\u_uart_tx/byte_in_reg[2] ),
        .I2(\tx_byte[3] ),
        .O(\u_uart_tx/n_33 )
    );
    defparam \_i_3/_i_32 .INIT = 8'HE4;

    xsLUTSA3 \_i_3/_i_33 
    (
        .I0(tx_req),
        .I1(\u_uart_tx/byte_in_reg[1] ),
        .I2(\tx_byte[2] ),
        .O(\u_uart_tx/n_32 )
    );
    defparam \_i_3/_i_33 .INIT = 8'HE4;

    xsLUTSA3 \_i_3/_i_34 
    (
        .I0(tx_req),
        .I1(\u_uart_tx/byte_in_reg[0] ),
        .I2(\tx_byte[1] ),
        .O(\u_uart_tx/n_31 )
    );
    defparam \_i_3/_i_34 .INIT = 8'HE4;

    xsLUTSA2 \_i_3/_i_35 
    (
        .I0(tx_req),
        .I1(\tx_byte[0] ),
        .O(\u_uart_tx/n_30 )
    );
    defparam \_i_3/_i_35 .INIT = 4'H8;

    xsLUTSA4 \_i_3/_i_36 
    (
        .I0(\_i_3/n106 ),
        .I1(\_i_3/n129 ),
        .I2(\u_uart_tx/n_47 ),
        .I3(tx_req),
        .O(\u_uart_tx/n_29 )
    );
    defparam \_i_3/_i_36 .INIT = 16'HFF02;

    xsLUTSA3 \_i_3/_i_37 
    (
        .I0(\_i_3/n106 ),
        .I1(\_i_3/n129 ),
        .I2(\u_uart_tx/n_47 ),
        .O(\u_uart_tx/n_40 )
    );
    defparam \_i_3/_i_37 .INIT = 8'H02;

    xsLUTSA2 \_i_3/_i_38 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/cnt[0] ),
        .O(\u_baud_pulse_gen/n_4 )
    );
    defparam \_i_3/_i_38 .INIT = 4'H1;

    xsLUTSA2 \_i_3/_i_39 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[1] ),
        .O(\u_baud_pulse_gen/n_5 )
    );
    defparam \_i_3/_i_39 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_40 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[2] ),
        .O(\u_baud_pulse_gen/n_6 )
    );
    defparam \_i_3/_i_40 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_41 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[3] ),
        .O(\u_baud_pulse_gen/n_7 )
    );
    defparam \_i_3/_i_41 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_42 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[4] ),
        .O(\u_baud_pulse_gen/n_8 )
    );
    defparam \_i_3/_i_42 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_43 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[5] ),
        .O(\u_baud_pulse_gen/n_9 )
    );
    defparam \_i_3/_i_43 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_44 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[6] ),
        .O(\u_baud_pulse_gen/n_10 )
    );
    defparam \_i_3/_i_44 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_45 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[7] ),
        .O(\u_baud_pulse_gen/n_11 )
    );
    defparam \_i_3/_i_45 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_46 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[8] ),
        .O(\u_baud_pulse_gen/n_12 )
    );
    defparam \_i_3/_i_46 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_47 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[9] ),
        .O(\u_baud_pulse_gen/n_13 )
    );
    defparam \_i_3/_i_47 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_48 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[10] ),
        .O(\u_baud_pulse_gen/n_14 )
    );
    defparam \_i_3/_i_48 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_49 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[11] ),
        .O(\u_baud_pulse_gen/n_15 )
    );
    defparam \_i_3/_i_49 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_50 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[12] ),
        .O(\u_baud_pulse_gen/n_16 )
    );
    defparam \_i_3/_i_50 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_51 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[13] ),
        .O(\u_baud_pulse_gen/n_17 )
    );
    defparam \_i_3/_i_51 .INIT = 4'H4;

    xsLUTSA2 \_i_3/_i_52 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/n_22[14] ),
        .O(\u_baud_pulse_gen/n_18 )
    );
    defparam \_i_3/_i_52 .INIT = 4'H4;

    xsLUTSA3 \_i_3/_i_53 
    (
        .I0(\_i_3/n106 ),
        .I1(\u_baud_pulse_gen/cnt[15] ),
        .I2(\u_baud_pulse_gen/cnt/_n_27 ),
        .O(\u_baud_pulse_gen/n_19 )
    );
    defparam \_i_3/_i_53 .INIT = 8'H14;

    xsINVSA \_i_3/_i_56 
    (
        .I(rst_n_c),
        .O(\u_baud_pulse_gen/n_0 )
    );
    xsLUTSA6 _i_0
    (
        .I0(\u_baud_pulse_gen/cnt[7] ),
        .I1(\u_baud_pulse_gen/cnt[6] ),
        .I2(\u_baud_pulse_gen/cnt[5] ),
        .I3(\u_baud_pulse_gen/cnt[4] ),
        .I4(\u_baud_pulse_gen/cnt[11] ),
        .I5(\u_baud_pulse_gen/cnt[10] ),
        .O(_n_0)
    );
    defparam _i_0.INIT = 64'H0000000000000800;

    xsLUTSA6 _i_1
    (
        .I0(\u_baud_pulse_gen/cnt[9] ),
        .I1(\u_baud_pulse_gen/cnt[8] ),
        .I2(\u_baud_pulse_gen/cnt[15] ),
        .I3(\u_baud_pulse_gen/cnt[14] ),
        .I4(\u_baud_pulse_gen/cnt[13] ),
        .I5(\u_baud_pulse_gen/cnt[12] ),
        .O(_n_1)
    );
    defparam _i_1.INIT = 64'H0000000000000001;

    xsLUTSA6 _i_2
    (
        .I0(\u_baud_pulse_gen/cnt[0] ),
        .I1(\u_baud_pulse_gen/cnt[3] ),
        .I2(\u_baud_pulse_gen/cnt[2] ),
        .I3(\u_baud_pulse_gen/cnt[1] ),
        .I4(_n_0),
        .I5(_n_1),
        .O(\_i_3/n106 )
    );
    defparam _i_2.INIT = 64'H0004000000000000;

    xsLUTSA5 _i_3
    (
        .I0(\u_uart_rx/n_78 ),
        .I1(\u_uart_rx/n_76 ),
        .I2(uart_rx_c),
        .I3(\_i_3/n119 ),
        .I4(\_i_3/n106 ),
        .O(\u_uart_rx/n_88 )
    );
    defparam _i_3.INIT = 32'H0CAEAAAA;

    xsLUTSA5 _i_4
    (
        .I0(\u_uart_tx/n_47 ),
        .I1(\u_uart_tx/n_45 ),
        .I2(tx_req),
        .I3(\_i_3/n125 ),
        .I4(\_i_3/n106 ),
        .O(\u_uart_tx/n_56 )
    );
    defparam _i_4.INIT = 32'H3B2AAAAA;

    xsLUTSA6 _i_5
    (
        .I0(\u_uart_tx/n_47 ),
        .I1(\u_uart_tx/n_45 ),
        .I2(tx_req),
        .I3(uart_tx_c),
        .I4(\_i_3/n127 ),
        .I5(\_i_3/n106 ),
        .O(\u_uart_tx/tx_reg_ctrl_din )
    );
    defparam _i_5.INIT = 64'HFFFF2A00FF00FF00;

    xsLUTSA3 _i_6
    (
        .I0(\u_uart_tx/n_47 ),
        .I1(\u_uart_tx/byte_in_reg[7] ),
        .I2(\_i_3/n129 ),
        .O(\_i_3/n127 )
    );
    defparam _i_6.INIT = 8'H54;

    xsLUTSA5 _i_7
    (
        .I0(\u_uart_tx/n_47 ),
        .I1(\u_uart_tx/n_45 ),
        .I2(tx_busy),
        .I3(tx_req),
        .I4(\_i_3/n106 ),
        .O(\u_uart_tx/busy_reg_ctrl_din )
    );
    defparam _i_7.INIT = 32'HFFD0F0F0;

    xsINVSA \_i_3/_i_54 
    (
        .I(\u_uart_rx/data_baud_cnt[0] ),
        .O(\u_uart_rx/n_74[0] )
    );
    xsINVSA \_i_3/_i_55 
    (
        .I(\u_uart_tx/data_baud_cnt[0] ),
        .O(\u_uart_tx/n_41[0] )
    );


endmodule
